### ISSUE TITLE
Installing GASSG

### ISSUE THREAD

**Issue by alex-mayfield** [ctsd/grav-gassg#1]
I appreciate this project. Turning Grav into an SSG would be great. I have not been able to access the plugins abilities, however. 

I placed this plugin within the /user/plugins folder, but am unable to see it. Is this the correct place to install? Thanks!

**Comment by ctsd** [comment]
Did you rename the plugin folder to "generator" ? It should be in /user/plugins, exactly as you did it .

**Comment by alex-mayfield** [comment]
Thanks that worked!
